openapi: 3.0.3
info:
  version: 1.0.0
  title: Swagger Petstore - OpenAPI 3.0
  description: test separate files
paths:
  /pet:
    $ref: 'pet/index.yaml#/collection'
  /pet/{petID}:
    $ref: 'entity.yaml'
